GET http://localhost:3416/manage/admin_manga
###
GET http://localhost:3416/manage/admin_manga/manga
###
GET http://localhost:3416/manage/admin_manga/61ffb19f0d300ec4ceb9b5c2
###
GET http://localhost:3416/manage/admin_manga/slide
###
GET http://localhost:3416/manage/admin_manga/slide/622233edefb0980400c35d77
###

POST  http://localhost:3416/manage/admin_manga/slide/
content-type: application/json

{
    "image": "/image/s3.jpg",
    "manga":"6223063c8a33d9fb7f629515"
}
///61ffb19f0d300ec4ceb9b5c2 - /image/s1.jpg
///6200b3232e8f26b60b590d1e - /image/s7.jpg
###
GET http://localhost:3416/manage/admin_manga/naruto/chapterImg

###
DELETE  http://localhost:3416/manage/admin_manga/slide/622233edefb0980400c35d77